version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-16-may-2021/luna-group-project/sagittarius/luna:latest
    ports:
      - 8000:8000
    env_file:
      - env/dev.env
    volumes:
      - ./backend:/backend
    command: "tail -f /dev/null"
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - env/dev.env
    volumes:
    - database:/var/lib/postgresql/data


volumes:
  database:
  static-files:
  media-files:
  frontend:
