# Generated by Django 3.2 on 2021-06-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='categories', to='restaurant.Restaurant'),
        ),
    ]
