# Generated by Django 3.2 on 2021-06-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openinghours', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghour',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='restaurant.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together={('weekday', 'from_hour', 'to_hour')},
        ),
    ]
