# Generated by Django 3.2 on 2021-06-29 10:20

import django.core.validators
from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[ 0-9]+$'), django.core.validators.MinLengthValidator(4)])),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. From 9 up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('price_level', models.IntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$')], default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant.models.user_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
